---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - PATH_PREFIX=/
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: yarn forestry:preview
  publish_command: yarn forestry:publish
  publish_env:
  - PATH_PREFIX=/
  output_directory: public
  preview_command: yarn forestry:publish
